Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [36]:
import numpy as np
import pandas as pd
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
df = pd.DataFrame([zp,ks])
cov = (zp*ks).mean()-zp.mean()*ks.mean()
cor = cov/(zp.std()*ks.std())
print(f' Ковариация {cov} \n {np.cov(zp,ks, ddof=0)} \n  Корреляция {cor} \n {np.corrcoef(zp,ks)}') 

 Ковариация 9157.839999999997 
 [[ 3494.64  9157.84]
 [ 9157.84 30468.89]] 
  Корреляция 0.8874900920739158 
 [[1.         0.88749009]
 [0.88749009 1.        ]]


In [47]:
df.corr()

0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
6  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
7  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
8  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
9  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.



In [55]:
from scipy.stats import norm
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
D_i = np.array([IQ.mean()-(2.262*IQ.std(ddof=1)/np.sqrt(len(IQ))),IQ.mean()+(2.262*IQ.std(ddof=1)/np.sqrt(len(IQ)))])
D_i

array([110.55660776, 125.64339224])

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [61]:
Di = np.array([174.2-(norm.ppf(0.95)*5/np.sqrt(27)),174.2+(norm.ppf(0.95)*5/np.sqrt(27))])
Di

array([172.61723886, 175.78276114])